name: build-windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO111MODULE: off

jobs:
  test:
    name: build-windows
    strategy:
      fail-fast: false
      matrix:
        go: [1.16.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os}}
    steps:
      - name: install golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: checkout code
        uses: actions/checkout@v2
      - name: go env
        run: |
          printf "$(go version)\n"
          printf "\n\ngo environment:\n\n"
          go get -u github.com/Lcfling/nbio/...
          go env
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: go test
        run: go test -covermode=atomic -timeout 60s -coverprofile="./coverage"
      - name: update code coverage report
        uses: codecov/codecov-action@v1.2.1
        with:
          files: "./coverage"
          flags: unittests
          verbose: true
          name: codecov-nbio